### ISSUE TITLE
Sporadic routing bug with static file routing

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#1050]
Traceback:

```
File "/usr/local/lib/python2.7/dist-packages/grow/server/main.py", line 28, in __call__
    return self.wsgi_app(environ, start_response)

File "/usr/local/lib/python2.7/dist-packages/grow/server/main.py", line 70, in wsgi_app
    response = self.dispatch_request(request)

File "/usr/local/lib/python2.7/dist-packages/grow/server/main.py", line 66, in dispatch_request
    return handlers.serve_pod(self.pod, request, matched)

File "/usr/local/lib/python2.7/dist-packages/grow/server/handlers.py", line 88, in serve_pod
    headers = controller.get_http_headers()

File "/usr/local/lib/python2.7/dist-packages/grow/rendering/render_controller.py", line 492, in get_http_headers
    path = self.pod.abs_path(self.static_doc.pod_path)

File "/usr/local/lib/python2.7/dist-packages/grow/rendering/render_controller.py", line 481, in static_doc
    self._static_doc = self.pod.get_static(self.pod_path, locale=locale)

File "/usr/local/lib/python2.7/dist-packages/grow/pods/pods.py", line 635, in get_static
    self, pod_path, locale=locale)

File "/usr/local/lib/python2.7/dist-packages/grow/documents/static_document.py", line 30, in __init__
    self.config = self.pod.router.get_static_config_for_pod_path(pod_path)

File "/usr/local/lib/python2.7/dist-packages/grow/routing/router.py", line 505, in get_static_config_for_pod_path
    if pod_path.startswith(static_dir):

'NoneType' object has no attribute 'startswith'
```

**Comment by jeremydw** [comment]
This seems to occur when pulling the latest from Git or updating a bunch of routes.

```
  File "/usr/local/lib/python2.7/dist-packages/grow/server/main.py", line 28, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/grow/server/main.py", line 70, in wsgi_app
    response = self.dispatch_request(request)
  File "/usr/local/lib/python2.7/dist-packages/grow/server/main.py", line 66, in dispatch_request
    return handlers.serve_pod(self.pod, request, matched)
  File "/usr/local/lib/python2.7/dist-packages/grow/server/handlers.py", line 88, in serve_pod
    headers = controller.get_http_headers()
  File "/usr/local/lib/python2.7/dist-packages/grow/rendering/render_controller.py", line 492, in get_http_headers
    path = self.pod.abs_path(self.static_doc.pod_path)
  File "/usr/local/lib/python2.7/dist-packages/grow/rendering/render_controller.py", line 481, in static_doc
    self._static_doc = self.pod.get_static(self.pod_path, locale=locale)
  File "/usr/local/lib/python2.7/dist-packages/grow/pods/pods.py", line 635, in get_static
    self, pod_path, locale=locale)
  File "/usr/local/lib/python2.7/dist-packages/grow/documents/static_document.py", line 30, in __init__
    self.config = self.pod.router.get_static_config_for_pod_path(pod_path)
  File "/usr/local/lib/python2.7/dist-packages/grow/routing/router.py", line 505, in get_static_config_for_pod_path
    if pod_path.startswith(static_dir):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by jeremydw** [comment]
This usually happens when the routing tree changes after the pod server has started.

**Comment by jeremydw** [comment]
This tends to happen on a live pod server, when adding a new route/document. Stepping through the traceback I think one of these two lines is the source of the bug:

https://github.com/grow/grow/blob/647377fe70f65d065875290aaa24e490b4db5970/grow/rendering/render_controller.py#L329
https://github.com/grow/grow/blob/647377fe70f65d065875290aaa24e490b4db5970/grow/rendering/render_controller.py#L308

The issue happens when a `RenderStaticDocumentController`'s `pod_path` is `None`.

**Comment by jeremydw** [comment]
This is still occurring. I think it's happening because the routing tree recalculation gets interrupted, and then it gets into an inconsistent state.

I found a traceback that might help debug:

```
Traceback (most recent call last):
  File "/Users/jeremydw/.local/share/virtualenvs/grow-cloud-run-ez-MnB7d/lib/python2.7/site-packages/grow/preprocessors/file_watchers.py", line 29, in trigger_file_changed
    self.pod.extensions_controller.trigger('dev_file_change', pod_path)
  File "/Users/jeremydw/.local/share/virtualenvs/grow-cloud-run-ez-MnB7d/lib/python2.7/site-packages/grow/extensions/extension_controller.py", line 52, in trigger
    return self._hooks[hook_key].trigger(*args, **kwargs)
  File "/Users/jeremydw/.local/share/virtualenvs/grow-cloud-run-ez-MnB7d/lib/python2.7/site-packages/grow/extensions/hook_controller.py", line 28, in trigger
    result = hook.trigger(result, *args, **kwargs)
  File "/Users/jeremydw/.local/share/virtualenvs/grow-cloud-run-ez-MnB7d/lib/python2.7/site-packages/grow/extensions/core/routes_extension.py", line 99, in trigger
    self._reset_routes(pod)
  File "/Users/jeremydw/.local/share/virtualenvs/grow-cloud-run-ez-MnB7d/lib/python2.7/site-packages/grow/extensions/core/routes_extension.py", line 88, in _reset_routes
    'dev_handler', pod.router.routes)
  File "/Users/jeremydw/.local/share/virtualenvs/grow-cloud-run-ez-MnB7d/lib/python2.7/site-packages/grow/extensions/extension_controller.py", line 52, in trigger
    return self._hooks[hook_key].trigger(*args, **kwargs)
  File "/Users/jeremydw/.local/share/virtualenvs/grow-cloud-run-ez-MnB7d/lib/python2.7/site-packages/grow/extensions/hook_controller.py", line 28, in trigger
    result = hook.trigger(result, *args, **kwargs)
TypeError: trigger() takes at least 5 arguments (3 given)
```

**Comment by jeremydw** [comment]
It might be unrelated but I also found that the `routescache.json` can get corrupted.

Here's a snippet from a corrupted file; I think it might be due to concurrent requests working on the routescache. We should (a) use a lock when writing the routescache locally and (b) if the server has trouble parsing the routescache file it should just delete it and start from scratch. 

Here's a snippet that shows the error the server encounters:
https://gist.githubusercontent.com/jeremydw/4449c95481545f7afa62c723c5463c4b/raw/fcf8a4bc754e95f4f6e1ccac1474174d5147902c/gistfile1.txt

```
      "/thank-you/": {
        "options": {},
        "value": {
          "hashed": "cadb8a96d3b83a031477640e663f6b6d4c18a58b78f9ffe4733017e181bb28e3",
          "kind": "doc",
          "meta": {
            "collection_path": "/content/pages",
            "locale": "en_US",
            "pod_path": "/content/pages/thank-you.yaml"
          },
          "pod_path": "/content/pages/thank-you.yaml"
        }
      }
    }
  },
  "version": 1
}kind": "doc",
          "meta": {
            "collection_path": "/content/pages",
            "locale": "en_US",
            "pod_path": "/content/pages/thank-you.yaml"
          },
          "pod_path": "/content/pages/thank-you.yaml"
        }
      }
    }
  },
  "version": 1
}
```

**Comment by Zoramite** [comment]
Going to close this for now unless there are other instances still causing issues.
