### ISSUE TITLE
Auto sitemap should only include documents with path formats

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#1064]
An error will occur if a document is added to the automatic sitemap but has no URL/path format. (See traceback below). This can be avoiding by checking for `doc.path_format` before accessing the `url` property on the `Document` object.

(Basically, the list of docs should filter out `Document` objects that don't have a `path_format`).

```
[20:38:10] Error building <grow.rendering.render_controller.RenderSitemapController object at 0x7f85f61dd0d0>: No path format found for <Document(/content/blog/foo.html, locale='en_US')>. You must specify a path format in either the blueprint or the document.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grow/rendering/render_controller.py", line 422, in render
    'podspec': self.pod.podspec,
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/grow/pods/templates/sitemap.xml", line 3, in top-level template code
    {% for doc in docs|sort(attribute='url') if not doc.sitemap.enabled is sameas false %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/filters.py", line 278, in do_sort
    return sorted(value, key=key_func, reverse=reverse)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/filters.py", line 77, in attrgetter
    item = environment.getitem(item, part)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 420, in getitem
    return getattr(obj, attr)
  File "/usr/local/lib/python2.7/dist-packages/grow/documents/document.py", line 422, in url
    path = self.get_serving_path()
  File "/usr/local/lib/python2.7/dist-packages/grow/common/utils.py", line 163, in __call__
    value = self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grow/documents/document.py", line 469, in get_serving_path
    'format in either the blueprint or the document.'.format(self))
PathFormatError: No path format found for <Document(/content/blog/foo.html, locale='en_US')>. You must specify a path format in either the blueprint or the document.
```

**Comment by jeremydw** [comment]
Fixed in https://github.com/grow/grow/commit/781094ae55829f7605e13dc8fbc6a8830644d752
