### ISSUE TITLE
Error from file watcher on document change

### ISSUE THREAD

**Issue by jon-loubert** [grow/grow#1081]
Using the `1.0.0-alpha.1` (Python 3) version, when I start a dev server with `grow run`, then make a change to a content YAML file, the console outputs this error:

```
[18:26:03] Found an error -> /content/pages/index.yaml
Traceback (most recent call last):
  File "grow/preprocessors/file_watchers.py", line 36, in trigger_file_changed
  File "grow/extensions/extension_controller.py", line 57, in trigger
  File "grow/extensions/hook_controller.py", line 28, in trigger
  File "grow/extensions/core/routes_extension.py", line 108, in trigger
  File "grow/collections/collection.py", line 433, in list_servable_document_locales
  File "grow/collections/collection.py", line 101, in _add_localized_docs
  File "grow/common/structures.py", line 184, in insert
TypeError: '<' not supported between instances of 'Document' and 'Document'
```
The server continues to work, but the changes to the document are ignored until I kill and restart the dev server.

**Comment by stevenle** [comment]
https://stackoverflow.com/questions/8276983/why-cant-i-use-the-method-cmp-in-python-3-as-for-python-2

**Comment by stevenle** [comment]
also: https://portingguide.readthedocs.io/en/latest/comparisons.html#rich-comparisons
