### ISSUE TITLE
Version Check on 1.0.0 alpha

### ISSUE THREAD

**Issue by Zoramite** [grow/grow#1083]
Version check isn't working correctly for the 1.0.0 alpha.

```
ERROR! Pod requires Grow SDK version: >=1.0.0
Traceback (most recent call last):
  File "grow", line 69, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "grow/commands/subcommands/run.py", line 44, in run
  File "grow/pods/pods.py", line 138, in __init__
  File "grow/sdk/updater.py", line 150, in verify_required_version
grow.sdk.updater.LatestVersionCheckError: ERROR! Pod requires Grow SDK version: >=1.0.0
```

**Comment by Zoramite** [comment]
I've updated it to get the version check to allow for alpha versions.

You will need to use something like this for the test: `grow_version: '>=1.0.0-alpha'`

Since `1.0.0-alpha < 1.0.0` the `>=1.0.0` will not match correctly.

I've updated the version check to append a `-` to the version check when it isn't included already which will [match the alpha versions](https://python-semanticversion.readthedocs.io/en/latest/#including-pre-release-identifiers-in-specifications) as well (in cases like `>= 0.8`)

Fixed in 9eba8b9be89abc95e0f4ec6f0ea4401f5e3edb06
