### ISSUE TITLE
Error using html_min extension on alpha3

### ISSUE THREAD

**Issue by bit-gerardorn** [grow/grow#1089]
https://github.com/grow/grow/blob/c8cb62e75a0ce17d80047af6a78f8f826003b367/grow/common/extensions.py#L105

Im testing the alpha3 pre-release. After installing the extension and trying to run grow run, I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/grow", line 69, in <module>
    group.grow()
  File "/home/gerardorn/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/gerardorn/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/gerardorn/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gerardorn/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gerardorn/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/gerardorn/.local/lib/python3.8/site-packages/grow/commands/subcommands/build.py", line 48, in build
    pod = pods.Pod(root, storage=storage.FileStorage)
  File "/home/gerardorn/.local/lib/python3.8/site-packages/grow/pods/pods.py", line 133, in __init__
    self._load_extensions(load_extensions)
  File "/home/gerardorn/.local/lib/python3.8/site-packages/grow/pods/pods.py", line 169, in _load_extensions
    self._extensions_controller.register_extensions(
  File "/home/gerardorn/.local/lib/python3.8/site-packages/grow/extensions/extension_controller.py", line 46, in register_extensions
    cls = common_extensions.import_extension(extension_path, [self.pod.root])
  File "/home/gerardorn/.local/lib/python3.8/site-packages/grow/common/extensions.py", line 87, in import_extension
    return import_extension(part2, [pathname])
  File "/home/gerardorn/.local/lib/python3.8/site-packages/grow/common/extensions.py", line 105, in import_extension
    result = getattr(module, part2)
AttributeError: module 'html_min' has no attribute 'HtmlMinExtension'

**Comment by Zoramite** [comment]
Thanks, I've [updated](https://github.com/grow/grow-ext-html-min/commit/8a5fd33a1053cf08728bb7b182b0267c25c262ca) the html-min extension, so it should work now with the python 3.
