### ISSUE TITLE
Can't install package due to broken pyyaml 5.4 dependency

### ISSUE THREAD

**Issue by stephenbunch** [grow/grow#1216]
I believe this is related to https://github.com/yaml/pyyaml/issues/724.

```
sbunch@sbunch:~/Downloads/checks$ poetry add grow
Creating virtualenv checks-adFXVFUm-py3.11 in /usr/local/google/home/sbunch/.cache/pypoetry/virtualenvs
Using version ^2.2.3 for grow

Updating dependencies
Resolving dependencies... (1.6s)

Package operations: 52 installs, 0 updates, 0 removals

  • Installing pyasn1 (0.5.0)
  • Installing cachetools (5.3.1)
  • Installing certifi (2020.4.5.2)
  • Installing charset-normalizer (2.0.12)
  • Installing idna (3.4)
  • Installing protobuf (3.20.3)
  • Installing pyasn1-modules (0.3.0)
  • Installing pyparsing (2.4.7)
  • Installing rsa (4.9)
  • Installing urllib3 (1.26.5)
  • Installing google-auth (2.23.3)
  • Installing googleapis-common-protos (1.60.0)
  • Installing httplib2 (0.19.0)
  • Installing requests (2.26.0)
  • Installing typing-extensions (4.8.0)
  • Installing google-api-core (1.34.0)
  • Installing google-auth-httplib2 (0.1.1)
  • Installing python-utils (3.8.1)
  • Installing six (1.16.0)
  • Installing smmap (5.0.1)
  • Installing uritemplate (3.0.1)
  • Installing gitdb (4.0.10)
  • Installing google-api-python-client (1.9.3)
  • Installing markupsafe (2.0.1)
  • Installing oauth2client (4.1.3)
  • Installing pathtools (0.1.2)
  • Installing progressbar2 (3.51.3)
  • Installing protorpc (0.12.0)
  • Installing pytz (2023.3.post1)
  • Installing soupsieve (1.9.6)
  • Installing text-unidecode (1.3)
  • Installing babel (2.9.1): Pending...
  • Installing beautifulsoup4 (4.9.1): Installing...
  • Installing boltons (20.1.0): Installing...
  • Installing cachelib (0.1)
  • Installing click (7.1.2): Pending...
  • Installing boltons (20.1.0): Installing...
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
  • Installing babel (2.9.1)
  • Installing beautifulsoup4 (4.9.1)
  • Installing boltons (20.1.0)
  • Installing cachelib (0.1)
  • Installing click (7.1.2)
  • Installing colored (1.4.2)
  • Installing gitpython (3.1.3)
  • Installing html2text (2020.1.16)
  • Installing jinja2 (2.11.3)
  • Installing markdown (3.3.4)
  • Installing pygments (2.7.4)
  • Installing python-slugify (4.0.0)
  • Installing pyyaml (5.4): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  /tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!
  
          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.
  
          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.
  
          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************
  
  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/usr/local/google/home/sbunch/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/google/home/sbunch/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/google/home/sbunch/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
      super().run_command(command)
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 318, in run
      self.find_sources()
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
      mm.run()
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 548, in run
      self.add_defaults()
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 201, in get_source_files
    File "/tmp/tmplodnnyln/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (5.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==5.4)"'.

  • Installing semantic-version (2.8.5)
  • Installing texttable-fixed (0.8.3)
  • Installing translitcodec (0.6.0)
  • Installing watchdog (0.10.2)
  • Installing webob (1.8.6)
  • Installing webreview (0.3.1)
  • Installing werkzeug (1.0.1)
```

**Comment by AllanPires95** [comment]
same as here! do you found how can fix that?
