### ISSUE TITLE
Bug with new --clear-auth flag

### ISSUE THREAD

**Issue by lluia** [grow/grow#201]
Hi, 

Thanks for the awesome work you're doing with **Grow** 😊

I would like to clarify if the new flag `--clear-auth` is working and if it should be ran like ` grow --clear-auth` or `grow run --clear-auth`?

I had the following issue the last days when trying to deploy to my staging server:
````bash
Building: 5562/5562 (in 0:00:42)
Refreshing access_token
Failed to retrieve access token: {
  "error" : "invalid_grant"
}
Traceback (most recent call last):
  File "<string>", line 81, in <module>
  File "growsdk/click.core", line 664, in __call__
  File "growsdk/click.core", line 644, in main
  File "growsdk/click.core", line 991, in invoke
  File "growsdk/click.core", line 837, in invoke
  File "growsdk/click.core", line 464, in invoke
  File "growsdk/grow.commands.stage", line 37, in stage
  File "growsdk/grow.deployments.destinations.webreview_destination", line 78, in deploy
  File "growsdk/grow.deployments.destinations.base", line 228, in deploy
  File "growsdk/grow.deployments.destinations.base", line 143, in _get_remote_index
  File "growsdk/grow.deployments.destinations.base", line 184, in read_control_file
  File "growsdk/grow.deployments.destinations.webreview_destination", line 101, in read_file
  File "growsdk/webreview.webreview", line 191, in read
  File "growsdk/webreview.webreview", line 157, in service
  File "growsdk/webreview.webreview", line 143, in get_service
  File "growsdk/oauth2client.client", line 597, in refresh
  File "growsdk/oauth2client.client", line 780, in _refresh
  File "growsdk/oauth2client.client", line 833, in _do_refresh_request
oauth2client.client.AccessTokenRefreshError: invalid_grant
````
However my access to the deployment server looked fine. I fixed it by removing manually the data from my *Keychain* (Mac). Also passing the following flag seems to solve the issue:
````bash
grow --auth your@email.com stage
````

**Comment by jeremydw** [comment]
Hi @lluia -- thanks for reporting this and for the detailed report! I ran into this issue yesterday myself. I think what's going on here is that `--clear-auth` works for preprocessors (e.g. if you oauth2 into the Google Drive API for the Google Sheets preprocessor) but not for WebReview. Let's leave this bug open while I verify and research a fix if needed. I believe we just need to propagate `--clear-auth` to the webreview client library (and increment the version used by Grow).

To clarify usage, `--clear-auth` is a global flag (just like `--auth`), so the correct use would indeed be:

```
grow --clear-auth <command>
grow --clear-auth run
grow --clear-auth stage
```

You're right that specifying `--auth` will override it, and the workaround in the meantime is to remove the data from Keychain on Mac.

**Comment by jeremydw** [comment]
This was released in https://github.com/grow/grow/releases/tag/0.0.61
