### ISSUE TITLE
Deploying multiple static_dirs to the same path?

### ISSUE THREAD

**Issue by vitorio** [grow/grow#212]
Two different content collections with `path: /{slug}` in their `_blueprint.yaml` works fine, but two `static_dir` locations don't.

To make managing some legacy content easier, in my `podspec.yaml` I have:

```
static_dirs:
- static_dir: /files/oldfiles1/
  serve_at: /
- static_dir: /files/oldfiles2/
  serve_at: /
```

There are no duplicate files, and all of them should show up deployed at the root.  I see two independent static routes in the `_grow` dashboard, but Grow only ever looks for files in the first `static_dir` location, even if they're a file in the second one.

It's not just a bug in the test server; trying to deploy this setup results in a crash:

```
[01:39:54] Error building: <Static(format='/files/oldfiles1/{filename}')>
Traceback (most recent call last):
  File "/Users/vitorio/Library/Python/2.7/bin/grow", line 81, in <module>
    grow()
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/grow/commands/deploy.py", line 44, in deploy
    paths_to_contents = deployment.dump(pod)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/grow/deployments/destinations/amazon_s3.py", line 51, in dump
    append_slashes=self.config.redirect_trailing_slashes)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/grow/pods/pods.py", line 313, in dump
    output = self.export()
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/grow/pods/pods.py", line 301, in export
    output[path] = controller.render(params)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/grow/pods/static.py", line 198, in render
    return self.pod.read_file(pod_path)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/grow/pods/pods.py", line 182, in read_file
    return self.storage.read(path)
  File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/grow/pods/storage/file_storage.py", line 18, in read
    fp = open(filename)
IOError: [Errno 2] No such file or directory: u'/Users/vitorio/Documents/personalsite-test/files/oldfiles1/reinventing-radio/rr50.png'
```

The folder and file there _is_ in `oldfiles2`, but it's looking for it in `oldfiles1`, and I'm not sure where or why.

**Comment by Zoramite** [comment]
I have a feeling that this is happening because of the usage of werkzeug routing, but I will take a closer look later to see if we can support this use case.

**Comment by Zoramite** [comment]
As far as the feature request, I think this would be the syntax that would make the most sense:

```
static_dirs:
- static_dir: 
  - /files/oldfiles1/
  - /files/oldfiles2/
  serve_at: /
```

Which would basically modify the static_dir to allow for an array of directories. This would definitely need to fail if there are duplicate (non-ignored) paths that would collide. But I don't see why this would not be possible.
