### ISSUE TITLE
Issue deploying to Git / gh-pages

### ISSUE THREAD

**Issue by apathetic** [grow/grow#269]
I'm having an issue deploying to a gh-pages branch on Github. I do not believe it to be an authentication issue as it pulls the gh-pages branch down initially with no problems. I'm not savvy in Python so am not able to make sense of the error messages I'm seeing -

From my podspec:

```
  test:
    destination: git
    repo: https://github.com/xxxxx/xxxxxx.git
    branch: gh-pages
```

After running ```grow deploy test``` the errors I'm seeing are (edited for clarity):

```
Warning: libyaml missing, using slower yaml parser.
Building: 57/57 (in 0:00:00)                                                                                                                                                                                                  
Pulling from gh-pages...
PASS Can write files to https://github.com/xxxxxx/xxxxxx.git@gh-pages:

Action                      Path                 Last deployed   By 
=====================================================================
add      /assets/css/main-2a7c55197ceeeb2d27863684814a4a2c.min.css                                             
...
[snip]
...

Diff: ..6d2cc3b (with unstaged changes) as wes.hatch@gmail.com
[6d2cc3b] 2016-08-03 <wes.hatch@gmail.com> adding dummy deploy for testing
...
[snip]
...

Proceed to deploy? -> https://github.com/xxxxxxx.git@gh-pages: [y/N]: y
Deploying: 57/57 (in 0:00:00)                                                                                                                                                                                                 
[6d2cc3b] 2016-08-03 <wes.hatch@gmail.com> adding dummy deploy for testing
...
[snip]
...

Traceback (most recent call last):
  File "/usr/local/bin/grow", line 81, in <module>
    grow()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/grow/commands/deploy.py", line 48, in deploy
    confirm=confirm, test=test)
  File "/usr/local/lib/python2.7/site-packages/grow/deployments/destinations/base.py", line 258, in deploy
    self.postlaunch()
  File "/usr/local/lib/python2.7/site-packages/grow/deployments/destinations/git_destination.py", line 107, in postlaunch
    self.repo.index.commit(self.create_commit_message())
  File "/usr/local/lib/python2.7/site-packages/grow/deployments/destinations/git_destination.py", line 82, in create_commit_message
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

**Comment by jeremydw** [comment]
Ack -- this is a bad bug. We'll go ahead and get this fixed (along with adding test coverage for Git-based deployments). Git-based deployment configs are not often used (rather folks have rolled their own Git deployment strategy using the local deployment). Thanks for reporting it.

**Comment by jeremydw** [comment]
Okay -- we've got the fix for this locally and have added a test. In order to ensure the best test coverage, can you let me know how you're authenticating to GitHub? Are you planning to use SSH or username/password?

**Comment by apathetic** [comment]
Sure - ideally I'd use SSH to authenticate

**Comment by jeremydw** [comment]
Alright -- we've got a fix for this committed, and also added coverage for both online and local repos. I can confirm that interactive auth works as well as key-based auth for deploying to remotes; so I think we should be good to go here. This fix should be available with the next release of Grow, which I hope we'll make in a day or two tops.
