### ISSUE TITLE
Grow extract dies if a Null override is tagged for translation

### ISSUE THREAD

**Issue by WillsB3** [grow/grow#292]
I had a document like this:

```yaml
...stuff and things...

description@: "My global description"
description@es@: ""
```

The reason for the override is we need to remove the description for one specific locale. The second `@` on the `description@es@` was really a mistake, but Grow renders pages with the mistake just fine. However when running `grow extract --localized` this causes a crash:

```
[17:02:15] Extracting: /path/to/my/document.yaml (2 locales)
Traceback (most recent call last):
  File "<string>", line 81, in <module>
  File "click/core.py", line 664, in __call__
  File "click/core.py", line 644, in main
  File "click/core.py", line 991, in invoke
  File "click/core.py", line 837, in invoke
  File "click/core.py", line 464, in invoke
  File "grow/commands/extract.py", line 50, in extract
  File "grow/pods/catalog_holder.py", line 267, in extract
  File "grow/common/utils.py", line 118, in walk
  File "grow/pods/catalog_holder.py", line 267, in <lambda>
  File "grow/pods/catalog_holder.py", line 203, in _handle_field
  File "grow/pods/catalog_holder.py", line 181, in _add_to_catalog
  File "babel/messages/catalog.py", line 601, in __setitem__
  File "babel/messages/catalog.py", line 237, in _parse_header
AttributeError: 'NoneType' object has no attribute 'encode'
grow returned -1
```

Untagging the description override allows `grow extract --localized` to complete successfully. 

Should we defend against this? It's really edge case and perhaps theres an easier way to "unset" a key (with `Null` or something?), but it's a still a relatively easy mistake to make. Perhaps we shouldn't even pass empty strings through to Babel at all?

**Comment by jeremydw** [comment]
I ran into this myself yesterday -- it's just a quick fix to exclude these from extraction. I don't think we need to do anything special when it comes to validation other than avoid extracting these into catalogs. Thanks for the report.
