### ISSUE TITLE
grow doesn't find content collections on Windows

### ISSUE THREAD

**Issue by vitorio** [grow/grow#349]
Seems like a different issue from #329 after all.

`grow run` launches for me on Windows 10 (native Python and git) but doesn't find any of my content collections, and doesn't report any errors.  `grow routes` only shows my Static routes, no collections or content.

I can make grow find the Collections initially by adding in the Windows path separator to `_normalize_path()` in `pods.py` around line 133:

```python
        return os.path.join(self.root, pod_path.lstrip('/\\'))
```

(Using `os.path.sep` doesn't seem to work.)

But, the resulting collections don't seem to be correct.  On Windows, `pods.py` function `get_collection()` reports:

```
collection.Collection.CONTENT_PATH /content
collection_path \content/posts
pod_path \content/posts
<Collection "\content/posts">
```

But on POSIX:

```
collection.Collection.CONTENT_PATH /content
collection_path /content/posts
pod_path /content/posts
<Collection "posts">
```

Further stripping out the Windows path separator in `collection.py` function `list_docs()` around line 247 seems to do the trick:

```python
            pod_path = os.path.join(self.pod_path, path.lstrip('/\\'))
```

Static files still seem to be causing trouble, haven't dug into that yet.

**Comment by vitorio** [comment]
Are static files served by `grow run` handled/routed/served differently than by `grow build`?

Static files aren't being served by `grow run` nor being deployed by `grow build` but I'm not seeing the debug prints that are being output by `grow build` when I do `grow run`.  If they're handled in two different places then it's two separate problems with the same symptoms as above: grow isn't translating the URL into a proper Windows host path.

Where is that conversion done for each?

**Comment by vitorio** [comment]
Ah, okay, the problem isn't URL/path conversion, it's text/binary content differences on Windows.  (On POSIX, files are files, but on Windows, text files have line endings inserted/modified and end at a null byte.)  grow `file_storage.py` (and possibly elsewhere) doesn't specify a mode string, which is fine on POSIX, but defaults to "plain text" on Windows, which means every binary file is treated like a text file, and breaks pretty quickly.

The problem then becomes that if you force everything to be opened as a binary file, grow gets thrown into a (literal) loop, that I don't understand, recursing on the same file over 600x until Python breaks:

```python
Traceback (most recent call last):
  File "env\Scripts\grow", line 86, in <module>
    grow()
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\commands\run.py", line 37, in run
    update_check=update_check)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\server\manager.py", line 70, in start
    serving.run_simple(host, port, app, request_handler=handler, threaded=True)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
    inner()
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\werkzeug\serving.py", line 656, in inner
    fd=fd)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\werkzeug\serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\werkzeug\serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "c:\python27\Lib\SocketServer.py", line 418, in __init__
    self.server_activate()
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\server\manager.py", line 25, in server_activate
    url = print_server_ready_message(self.pod, self.pod.env.host, port)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\server\manager.py", line 37, in print_server_ready_message
    root_path = home_doc.url.path
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\documents.py", line 131, in url
    path = self.get_serving_path()
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\common\utils.py", line 142, in __call__
    value = self.func(*args, **kwargs)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\documents.py", line 223, in get_serving_path
    locale = str(self.locale)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\common\utils.py", line 192, in __get__
    value = self.func(obj)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\documents.py", line 56, in locale
    self._locale = self._init_locale(self._locale_kwarg, self.pod_path)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\documents.py", line 66, in _init_locale
    locale, default=self.default_locale)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\common\utils.py", line 192, in __get__
    value = self.func(obj)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\documents.py", line 93, in default_locale
    if (self.fields.get('$localization')
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\documents.py", line 82, in __getattr__
    return self.fields[name]
# repeat the above line over 600 times
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\common\utils.py", line 192, in __get__
    value = self.func(obj)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\documents.py", line 105, in fields
    tagged_fields = self.get_tagged_fields()
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\documents.py", line 110, in get_tagged_fields
    format = formats.Format.get(self)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\formats.py", line 133, in get
    return HtmlFormat(doc)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\formats.py", line 40, in __init__
    self.content = self._init_content()
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\formats.py", line 107, in _init_content
    if self.doc.pod.file_exists(self.pod_path):
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\pods.py", line 168, in file_exists
    path = self._normalize_path(pod_path)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\site-packages\grow\pods\pods.py", line 134, in _normalize_path
    return os.path.join(self.root, pod_path.lstrip('/'))
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\vitorio\Documents\vitoriosite\env\lib\ntpath.py", line 117, in splitdrive
    if (normp[0:2] == sep*2) and (normp[2:3] != sep):
RuntimeError: maximum recursion depth exceeded in cmp
```

I've hacked around this in `file_storage.py` function `read()` by forcing HTML and Markdown files to be opened as text files, but I don't understand what the problem is:

```python
    @staticmethod
    def read(filename):
        if os.path.splitext(filename)[1] == '.md' or os.path.splitext(filename)[1] == '.html':
            fp = open(filename)
        else:
            fp = open(filename, 'rb')
        content = fp.read()
        fp.close()
        return content
```

Forcing all files to be opened in binary mode on my OS X machine doesn't seem to affect anything at all (but might in Python 3, where bytes are different from Unicode strings?).
