### ISSUE TITLE
Watchdog error on Linux on 0.1.1

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#398]
Some users are having trouble running the development server on Linux on 0.1.1. Seems like a watchdog issue, traceback below -

```
$ grow run
Traceback (most recent call last):
 File "grow", line 86, in <module>
 File "site-packages/click/core.py", line 722, in __call__
 File "site-packages/click/core.py", line 697, in main
 File "site-packages/click/core.py", line 1066, in invoke
 File "site-packages/click/core.py", line 895, in invoke
 File "site-packages/click/core.py", line 535, in invoke
 File "grow/commands/run.py", line 44, in run
 File "grow/server/manager.py", line 50, in start
 File "grow/preprocessors/file_watchers.py", line 132, in create_dev_server_observers
 File "grow/preprocessors/file_watchers.py", line 105, in start
 File "grow/preprocessors/file_watchers.py", line 106, in start
 File "site-packages/watchdog/observers/api.py", line 255, in start
 File "site-packages/watchdog/utils/__init__.py", line 111, in start
 File "site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
 File "site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
 File "site-packages/watchdog/observers/inotify_c.py", line 187, in __init__
 File "site-packages/watchdog/observers/inotify_c.py", line 363, in _add_dir_watch
OSError: Path is not a directory
Failed to execute script grow
```

/cc @mhchen

**Comment by Zoramite** [comment]
This appears to be an issue with the path not existing for some of the built-in preprocessor. For instance, if there is not a `/translations` directory it fails in a different place in Linux than in OSX.

36ed8b2d21da0ae7cd8dd5140920183b11565112 Fixes this by checking that the path is a directory before creating adding to the watchers.
