### ISSUE TITLE
Build to github return error (TypeError: bufsize must be an integer)

### ISSUE THREAD

**Issue by nicloay** [grow/grow#406]
I use 0.1.2 version on MacOS

```
nicloay:workspace nicloay$ grow deploy github.io mysite
...
Proceed to deploy? -> git@github.com:path_removed.io.git@master: [y/N]: y
Deploying: 139/139 (in 0:00:00)
Traceback (most recent call last):
  File "grow", line 86, in <module>
  File "click/core.py", line 722, in __call__
  File "click/core.py", line 697, in main
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 895, in invoke
  File "click/core.py", line 535, in invoke
  File "click/decorators.py", line 17, in new_func
  File "grow/commands/deploy.py", line 48, in deploy
  File "grow/deployments/destinations/base.py", line 258, in deploy
  File "grow/deployments/destinations/git_destination.py", line 110, in postlaunch
  File "grow/deployments/destinations/git_destination.py", line 90, in create_commit_message
  File "subprocess.py", line 168, in call
  File "subprocess.py", line 339, in __init__
TypeError: bufsize must be an integer
Failed to execute script grow
```

and here is my environment
```
nicloay:workspace nicloay$ echo $EDITOR
vim
nicloay:workspace nicloay$ vim
nicloay:workspace nicloay$ export EDITOR=""
```
I've checked that vim works fine, and then removed EDITOR variable and only after that push happens.

**Comment by Zoramite** [comment]
@nicloay is this still an issue? Sorry we haven't replied to it yet, but we have made some updates recently to the git dependency and that may have fixed the issue.
