### ISSUE TITLE
Unhelpful error messaging when podspec deployments are malformed.

### ISSUE THREAD

**Issue by TomSlezakowski** [grow/grow#438]
Not really a bug, but a helpful suggestion.

When switching to a newer version of Grow, we found ourselves stuck being unable to deploy to appspot with the following config:
```
appspot-test:
     destination: somewhere
     server: something.appspot.com
     project: something/some-name
     subdomain:
     name: somename
```
This causes the following error : 

```
Traceback (most recent call last):
  File "grow", line 86, in <module>
  File "click/core.py", line 722, in __call__
  File "click/core.py", line 697, in main
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 895, in invoke
  File "click/core.py", line 535, in invoke
  File "click/decorators.py", line 17, in new_func
  File "grow/commands/deploy.py", line 42, in deploy
  File "grow/pods/pods.py", line 627, in preprocess
  File "grow/preprocessors/gulp.py", line 29, in run
  File "grow/common/sdk_utils.py", line 110, in get_popen_args
AttributeError: 'NoneType' object has no attribute 'name'
Failed to execute script grow
```

The cause of this, is that there is no env definition within the podspec config, but the error doesn't help one find the missing detail without going through grow's own src.

The final config should look like so :

```
appspot-test:
     destination: somewhere
     server: something.appspot.com
     project: something/some-name
     subdomain:
     name: somename
     env:
          name: someothername
```

**Comment by jeremydw** [comment]
Based on the traceback it looks like something else might be going on here - I don't think this is actually an issue with `grow stage` but rather use of `{{env.name}}` in a template. Would you mind pinging me (privately is OK if the sources are not public) the location of your source code to this repository and I can take a look?
