### ISSUE TITLE
Error installing theme

### ISSUE THREAD

**Issue by grupie001** [grow/grow#462]
hi there,
first I am a really, really beginner with the shell. So please don't beat me for this (maybe stupid) question.
I installed Grow, run it, but when installing the theme I get following error message at the end:
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED].....
Failed to execute script grow

Any advice what I have made wrong?

**Comment by jeremydw** [comment]
Hi there - sorry you've run into this problem. Can you make sure you're using the latest version of Grow, where we pack certificates into the release?

Separately - the theme install is just a lightweight wrapper for a `git clone` to any of the repositories listed here - https://github.com/growthemes - you can try `git clone`ing one of those instead.

Can you provide a little more debugging info? What system/environment are you using? Thanks!

**Comment by Zoramite** [comment]
Closing for now since we don't have more information. If you have more details to provide after updating grow then reopen the issue.

**Comment by bpaduch** [comment]
Got this same issue today.  Wanted to refresh my understanding of grow, ran the following:

```
grow init codelab ./my-codelab/
```

Received the following error:

```
Traceback (most recent call last):
  File "grow", line 58, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "grow/commands/subcommands/init.py", line 25, in init
  File "grow/pods/themes.py", line 24, in init
  File "grow/pods/themes.py", line 75, in clone
  File "site-packages/dulwich/client.py", line 363, in fetch
  File "site-packages/dulwich/client.py", line 1398, in fetch_pack
  File "site-packages/dulwich/client.py", line 1282, in _discover_references
  File "site-packages/dulwich/client.py", line 1261, in _http_request
  File "urllib2.py", line 429, in open
  File "urllib2.py", line 447, in _open
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 1241, in https_open
  File "urllib2.py", line 1198, in do_open
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
[11831] Failed to execute script grow
```

Using: Grow version 4.0
OS: Mac High Sierra

**Comment by mmccoy** [comment]
Was kicking off a new project this morning after upgrading to 0.4.0 last week, and received this error as well. (FYI, I happen to be trying to init the base theme)

@bpaduch 
I believe a workaround could be just to clone the theme repo directly from github and start there.  I'm not sure what other magic `grow init` may do, but the following seemed to work okay for me when I ran into the cert issue:

```
git clone https://github.com/growthemes/codelab.git ./grow-codelab
cd grow-codelab
grow run
```

-mm
