### ISSUE TITLE
Error UnicodeEncodeError when build with user name is Unicode characters

### ISSUE THREAD

**Issue by chammua** [grow/grow#470]
Hi guys,

Currently I have configure git name contain Unicode character when I build a pod with command: `grow build` I received error message as:
```
Traceback (most recent call last):
  File "/usr/local/bin/grow", line 92, in <module>
    grow()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grow/commands/build.py", line 35, in build
    test=False)
  File "/usr/local/lib/python2.7/dist-packages/grow/deployments/destinations/base.py", line 251, in deploy
    indexes.Diff.pretty_print(diff)
  File "/usr/local/lib/python2.7/dist-packages/grow/deployments/indexes.py", line 63, in pretty_print
    file_rows.append(cls._make_diff_row(texttable.bcolors.PURPLE, 'edit', edit))
  File "/usr/local/lib/python2.7/dist-packages/grow/deployments/indexes.py", line 44, in _make_diff_row
    formatted_author = cls._format_author(message.deployed_by, True)
  File "/usr/local/lib/python2.7/dist-packages/grow/deployments/indexes.py", line 37, in _format_author
    return '{} <{}>'.format(author.name, author.email) if author else ''
UnicodeEncodeError: 'ascii' codec can't encode character u'\u1ea5' in position 2: ordinal not in range(128)
```
As I know at line 37 in file `indexes.py` of file has path: `/usr/local/lib/python2.7/dist-packages/grow/deployments/indexes.py` don't unicode string, so I have fix it with code:
```
    return '{} <{}>'.format(author.name.encode('utf-8').strip(), author.email.encode('utf-8').strip()) if author else ''
```
and it's work fine. 

I'm using `grow` version: `0.2.0`

Thanks,

**Comment by jeremydw** [comment]
Thanks for reporting this! I just committed https://github.com/grow/grow/commit/eb9d00987b0c5a11964a122446c66ddc2e87b266 with a fix - so it will be fixed in the next release.
