### ISSUE TITLE
Issue using keyring module in Linux

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#521]
Traceback:

```
Building: 297/297 (in 0.377383)                                                                                                                                
Traceback (most recent call last):
  File "grow", line 92, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "grow/commands/stage.py", line 39, in stage
  File "grow/deployments/destinations/webreview_destination.py", line 105, in deploy
  File "grow/deployments/destinations/base.py", line 258, in deploy
  File "grow/deployments/destinations/base.py", line 158, in _get_remote_index
  File "grow/deployments/destinations/base.py", line 214, in read_control_file
  File "grow/deployments/destinations/webreview_destination.py", line 133, in read_file
  File "site-packages/webreview/webreview.py", line 277, in read
  File "site-packages/webreview/webreview.py", line 258, in get_signed_requests
  File "site-packages/webreview/webreview.py", line 164, in get_service
  File "site-packages/webreview/webreview.py", line 205, in get_credentials
  File "site-packages/oauth2client/client.py", line 409, in get
  File "site-packages/oauth2client/contrib/keyring_storage.py", line 72, in locked_get
  File "site-packages/keyring/core.py", line 42, in get_password
  File "site-packages/keyring/backends/fail.py", line 18, in get_password
```

**Comment by Zoramite** [comment]
We removed keyring.
