### ISSUE TITLE
Errors encountered by file watchers require grow restart

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#528]
When a file watcher encounters an error, it seems to require a restart of the dev server for future YAML changes to be picked up.

```
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "watchdog/observers/api.py", line 199, in run
  File "watchdog/observers/api.py", line 368, in dispatch_events
  File "watchdog/events.py", line 454, in dispatch
  File "grow/preprocessors/file_watchers.py", line 23, in on_created
  File "grow/preprocessors/file_watchers.py", line 19, in handle
  File "grow/pods/pods.py", line 599, in on_file_changed
  File "grow/pods/pods.py", line 388, in get_doc
  File "grow/pods/collection.py", line 255, in get_doc
  File "grow/pods/documents.py", line 74, in __init__
  File "grow/common/utils.py", line 134, in validate_name
BadNameError: Names must be lowercase and only contain letters, numbers, backslashes, and dashes. Found: "/content/modules/foo copy.yaml"
```

**Comment by jeremydw** [comment]
FYI - I was able to reproduce this error by duplicating a content YAML file in macOS. Basically, macOS renames the file to `file (copy).yaml` and the presence of the space in the duplicated file causes Grow to die. You can reproduce it by using Finder to duplicate any file in `/content/`.
