### ISSUE TITLE
Problem installing Grow on LXLE (ubuntu based)

### ISSUE THREAD

**Issue by NetLancer** [grow/grow#561]
It's been a long time i got stuck at the installation stage. The result is:

[✓] Installed Grow SDK to: /home/me/bin/grow
Traceback (most recent call last):
  File "/tmp/tmp.2Hd2rwsqU7/install_growsdk.py", line 208, in <module>
    main()
  File "/tmp/tmp.2Hd2rwsqU7/install_growsdk.py", line 204, in main
    install(rc_path=args.rc_path, bin_path=args.bin_path, force=args.force)
  File "/tmp/tmp.2Hd2rwsqU7/install_growsdk.py", line 180, in install
    fp = open(rc_path, 'a')
IOError: [Errno 13] Permission denied: '/home/me/.bash_profile'
me@Easynote-TE69CX:~$ 

And here's what SUDO gives:

Downloading from https://github.com/grow/grow/releases/download/0.2.8/Grow-SDK-Linux-0.2.8.zip
.......Traceback (most recent call last):
  File "/tmp/tmp.BwG4G039Lv/install_growsdk.py", line 208, in <module>
    main()
  File "/tmp/tmp.BwG4G039Lv/install_growsdk.py", line 204, in main
    install(rc_path=args.rc_path, bin_path=args.bin_path, force=args.force)
  File "/tmp/tmp.BwG4G039Lv/install_growsdk.py", line 153, in install
    content = remote.read(1048576)  # 1MB.
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer

It seems I've tries many things to solve this and two last releases 0.27 & 0.28, nothing helped.
Now grow command gives 'Segmentation Fault' issue.
Cry for help !!

**Comment by Zoramite** [comment]
Hi @NetLancer I think that the first time you did it the process was pretty much complete except for adding and alias to your `.bash_profile`. You could test this by trying to do `/home/me/bin/grow build` in a directory you are trying to add grow to. If that works then you can edit the `.bash_profile` doc to have an alias for the command: alias grow='/home/me/bin/grow'

**Comment by NetLancer** [comment]
Hi @Zoramite! Here's the outcome (yet there's nothing understandable to me :))

Traceback (most recent call last):
  File "grow", line 86, in <module>
    
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "grow/commands/build.py", line 27, in build
  File "grow/pods/pods.py", line 619, in preprocess
  File "grow/common/utils.py", line 147, in __call__
  File "grow/pods/pods.py", line 518, in list_preprocessors
  File "grow/pods/pods.py", line 172, in yaml
  File "grow/common/utils.py", line 147, in __call__
  File "grow/pods/pods.py", line 118, in _parse_yaml
grow.pods.pods.PodDoesNotExistError: Pod not found in: /home/ellie/bin/podspec.yaml
Failed to execute script grow
ellie@debian:~/bin$

**Comment by Zoramite** [comment]
It looks correct, you just are not running the command in a directory that you have a pod in. (There should be a `podspec.yaml` file in the directory. So I would add in the alias to the `~/.bash_profile` and it should work when you need to run grow in a project.
