### ISSUE TITLE
Error rendering style

### ISSUE THREAD

**Issue by molavec** [grow/grow#663]
## Description

Error in render when add a # selector inside of media rule.

I tried insert css style in two ways in base.html

    <link rel="stylesheet" href="{{g.static('/dist/main.min.css').url.path}}">

and..

    <style>
      {% include "/dist/main.min.css" %}
    </style>

## How to reproduce

Just with codelab inital project

    grow init codelab ./codelab

Add a # selector inside of @media rule in main.scss file (at the end).

    @media screen and (max-width:768px){
      #hero-home{
        background-position:top 0 right 700px
      }
    }

produce a error rendering

    Error building <Rendered(view='/views/index.html', doc='/content/pages/index.md', locale='en')>: Missing end of comment tag
    Traceback (most recent call last):
      File "/Users/angel/Library/Python/2.7/lib/python/site-packages/grow/pods/rendered.py", line 93, in render
        content = template.render(kwargs).lstrip()
      File "/Users/angel/Library/Python/2.7/lib/python/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/Users/angel/Library/Python/2.7/lib/python/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "<unknown>", line 4, in template
    TemplateSyntaxError: Missing end of comment tag
    500: / - Error building <Rendered(view='/views/index.html', doc='/content/pages/index.md', locale='en')>: Missing end of comment tag
    Traceback (most recent call last):
      File "/Users/angel/Library/Python/2.7/lib/python/site-packages/grow/server/main.py", line 166, in __call__
        return self.wsgi_app(environ, start_response)
      File "/Users/angel/Library/Python/2.7/lib/python/site-packages/grow/server/main.py", line 161, in wsgi_app
        response = self.dispatch_request(request)
      File "/Users/angel/Library/Python/2.7/lib/python/site-packages/grow/server/main.py", line 155, in dispatch_request
        return endpoint(self.pod, request, values)
      File "/Users/angel/Library/Python/2.7/lib/python/site-packages/grow/server/main.py", line 77, in serve_pod
        content = controller.render(params)
      File "/Users/angel/Library/Python/2.7/lib/python/site-packages/grow/pods/rendered.py", line 106, in render
        raise exception
    BuildError: Error building <Rendered(view='/views/index.html', doc='/content/pages/index.md', locale='en')>: Missing end of comment tag

with class **(dot)** selector everything it's ok!

**Comment by Zoramite** [comment]
In Jinja the `{#` is how a comment is done. Trying to directly include into the temple is probably breaking because of how the sass is being minified.

Ideally the css would be in a separate file instead of directly imported in the template. Is there a reason that you would need it to be inline?

I'll check into it more next week, but the first example of the URL to the css is the normal way to do it.

**Comment by molavec** [comment]
Thanks you. 

In [AMP](https://www.ampproject.org) is necessary to include css inline. For that reason do it the inline way.

**Comment by Zoramite** [comment]
Alright, another thing you can try is to use the gulp sass to see if that does a better job of how it minifies the css, like in the [base theme](https://github.com/growthemes/base) (ex: `grow init base`)

Another possibility is to not do an include (psuedo code):

```
{{doc.pod.read_file('/dist/main.min.css')|safe}}
```

**Comment by Zoramite** [comment]
@molavec Did that work to directly output from the `pod.read_file()`?
