### ISSUE TITLE
Babel error in `grow run`

### ISSUE THREAD

**Issue by stevenle** [grow/grow#670]
Traceback:

```
grow run --port=8080 --no-ui --no-update-check .
Traceback (most recent call last):
  File "grow", line 58, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1092, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "grow/commands/subcommands/run.py", line 47, in run
  File "grow/pods/pods.py", line 129, in __init__
  File "grow/common/sdk_utils.py", line 66, in check_sdk_version
  File "grow/pods/pods.py", line 249, in grow_version
  File "grow/pods/pods.py", line 275, in podspec
  File "grow/pods/podspec.py", line 21, in __init__
  File "grow/pods/locales.py", line 65, in parse
  File "site-packages/babel/core.py", line 381, in get_display_name
  File "site-packages/babel/core.py", line 482, in languages
  File "site-packages/babel/localedata.py", line 218, in __getitem__
KeyError: 'languages'
[1951] Failed to execute script grow
```

**Comment by Zoramite** [comment]
Closed by https://github.com/grow/grow/commit/9aee07b0ab9e93f9c740a88b591da19973cf295e
