### ISSUE TITLE
Keyring fails in OSX High Sierra

### ISSUE THREAD

**Issue by Zoramite** [grow/grow#677]
When trying to build in the latest version of OSX there is an issue with oauth not being able to use the keyring:

```
Traceback (most recent call last):
  File "grow/scripts/../bin/grow", line 58, in <module>
    group.grow()
  File "grow/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "grow/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "grow/env/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "grow/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "grow/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "grow/bin/../grow/commands/subcommands/build.py", line 75, in build
    test=False, is_partial=bool(pod_paths))
  File "grow/bin/../grow/deployments/destinations/base.py", line 283, in deploy
    deployed_index, content_generator, repo=repo, is_partial=is_partial)
  File "grow/bin/../grow/deployments/indexes.py", line 316, in stream
    for rendered_doc in content_generator:
  File "grow/bin/../grow/pods/pods.py", line 389, in dump
    suffix=suffix, append_slashes=append_slashes, pod_paths=pod_paths):
  File "grow/bin/../grow/pods/pods.py", line 407, in export
    paths, routes, suffix=suffix, append_slashes=append_slashes):
  File "grow/bin/../grow/pods/pods.py", line 927, in render_paths
    output_path, controller.render(params, inject=False),
  File "grow/bin/../grow/pods/rendered.py", line 106, in render
    raise exception
grow.pods.errors.BuildError: Error building <Rendered(view='/views/base.html', doc='/content/pages/entertainment.yaml', locale='ja_JP')>: (-25293, "Can't fetch password from system")
```

**Comment by Zoramite** [comment]
This seems to happen on OSX when the python binary is not signed (such as coming from brew).

`codesign -f -s - ./env/bin/python` will sign the python as adhoc and should fix the issue with the keychain.
