### ISSUE TITLE
"grow stage" error: UnboundLocalError: local variable 'flow' referenced before assignment

### ISSUE THREAD

**Issue by ciampo** [grow/grow#738]
This issue is quite urgent as it's currently preventing me from publishing new staging links to WebReview

grow version: 0.3.20

Complete error message

```
Traceback (most recent call last):
  File "grow", line 58, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "grow/commands/subcommands/stage.py", line 66, in stage
  File "grow/deployments/destinations/webreview_destination.py", line 105, in deploy
  File "grow/deployments/destinations/base.py", line 279, in deploy
  File "grow/deployments/destinations/base.py", line 163, in _get_remote_index
  File "grow/deployments/destinations/base.py", line 232, in read_control_file
  File "grow/deployments/destinations/webreview_destination.py", line 133, in read_file
  File "site-packages/webreview/webreview.py", line 300, in read
  File "site-packages/webreview/webreview.py", line 277, in get_signed_requests
  File "site-packages/webreview/webreview.py", line 182, in get_service
  File "site-packages/webreview/webreview.py", line 229, in get_credentials
UnboundLocalError: local variable 'flow' referenced before assignment
[15504] Failed to execute script grow
```

**Comment by ciampo** [comment]
Update: using the `--clear-auth` seems to avoid the error.

It probably still makes sense to handle this exception better, maybe showing an error or even forcing the authentication automatically?

**Comment by Zoramite** [comment]
Thanks, this error is actual in the webreview dependency, so I am going to move it over there.
