### ISSUE TITLE
stage fails when `localization` key not present in podspec

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#740]
Traceback:

```
$ grow stage -np
Traceback (most recent call last):
  File "grow", line 58, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "grow/commands/subcommands/stage.py", line 49, in stage
AttributeError: 'NoneType' object has no attribute 'get'
```

Problematic line:
https://github.com/grow/grow/blob/master/grow/commands/subcommands/stage.py#L49

**Comment by alentodorov** [comment]
Build as well. Took me a while to figure that was the problem. I’m sorry I didn’t came back to update my first issue.

**Comment by jeremydw** [comment]
@Zoramite can you make a quick fix here? Looks like we just need to check for `localization` before trying to reference a property on it.
