### ISSUE TITLE
keyring issue

### ISSUE THREAD

**Issue by stevenle** [grow/grow#802]
In one of the more recent versions of grow (> `0.5.2` I believe), I've been getting the following error when running anything related to sheets preprocessors:

```
Traceback (most recent call last):
  File "grow", line 76, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "grow/commands/subcommands/preprocess.py", line 42, in preprocess
  File "grow/pods/pods.py", line 778, in preprocess
  File "grow/preprocessors/google_drive.py", line 51, in run
  File "grow/preprocessors/google_drive.py", line 338, in execute
  File "grow/preprocessors/google_drive.py", line 191, in download
  File "grow/preprocessors/google_drive.py", line 44, in create_service
  File "grow/common/oauth.py", line 64, in get_or_create_credentials
  File "grow/common/oauth.py", line 48, in get_credentials_and_storage
  File "site-packages/oauth2client/client.py", line 409, in get
  File "site-packages/oauth2client/contrib/keyring_storage.py", line 72, in locked_get
  File "site-packages/keyring/core.py", line 41, in get_password
  File "site-packages/keyring/backends/fail.py", line 23, in get_password
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
[23177] Failed to execute script grow
```

Running on Mac, grow version 0.5.4.

**Comment by stevenle** [comment]
just tried on linux as well, getting:

```
$ grow preprocess -p offices
Attempting refresh to obtain initial access_token
Traceback (most recent call last):
  File "bin/grow", line 76, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "grow/commands/subcommands/preprocess.py", line 42, in preprocess
  File "grow/pods/pods.py", line 778, in preprocess
  File "grow/preprocessors/google_drive.py", line 51, in run
  File "grow/preprocessors/google_drive.py", line 338, in execute
  File "grow/preprocessors/google_drive.py", line 191, in download
  File "grow/preprocessors/google_drive.py", line 47, in create_service
  File "site-packages/oauth2client/util.py", line 137, in positional_wrapper
  File "site-packages/googleapiclient/discovery.py", line 198, in build
  File "site-packages/oauth2client/transport.py", line 153, in new_request
  File "site-packages/oauth2client/contrib/appengine.py", line 178, in _refresh
  File "google/appengine/api/app_identity/app_identity.py", line 600, in get_access_token
  File "google/appengine/api/memcache/__init__.py", line 562, in get
  File "google/appengine/api/memcache/__init__.py", line 619, in get_multi_async
  File "google/appengine/api/memcache/__init__.py", line 385, in _make_async_call
  File "google/appengine/api/memcache/__init__.py", line 297, in create_rpc
  File "google/appengine/api/apiproxy_stub_map.py", line 414, in __init__
  File "google/appengine/api/apiproxy_stub_map.py", line 68, in CreateRPC
AssertionError: No api proxy found for service "memcache"
[3101] Failed to execute script grow

$ grow --version                                                                                                                             
0.5.4      
```

not sure why the system thinks i'm on app engine. i'm running archlinux.

**Comment by Zoramite** [comment]
#804 should have fixed this issue for now. If you have more issues, especially with the memcache issue let me know.
