### ISSUE TITLE
Pre-packaged Linux binary thinks user is on App Engine

### ISSUE THREAD

**Issue by stevenle** [grow/grow#805]
The Google Sheets preprocessor seems to think I'm running on App Engine for some reason. I believe this is happening in https://github.com/grow/grow/blob/master/grow/common/oauth.py, where we determine if we're running on App Engine or not based on whether the import fails. Can we switch to a more deterministic way of checking if the user is on App Engine?

```
[15:30:31] Compiled: en_US (280/332)
Attempting refresh to obtain initial access_token
Traceback (most recent call last):
  File "bin/grow", line 76, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "grow/commands/subcommands/preprocess.py", line 42, in preprocess
  File "grow/pods/pods.py", line 781, in preprocess
  File "grow/preprocessors/google_drive.py", line 51, in run
  File "grow/preprocessors/google_drive.py", line 338, in execute
  File "grow/preprocessors/google_drive.py", line 191, in download
  File "grow/preprocessors/google_drive.py", line 47, in create_service
  File "site-packages/oauth2client/util.py", line 137, in positional_wrapper
  File "site-packages/googleapiclient/discovery.py", line 198, in build
  File "site-packages/oauth2client/transport.py", line 153, in new_request
  File "site-packages/oauth2client/contrib/appengine.py", line 178, in _refresh
  File "google/appengine/api/app_identity/app_identity.py", line 600, in get_access_token
  File "google/appengine/api/memcache/__init__.py", line 562, in get
  File "google/appengine/api/memcache/__init__.py", line 619, in get_multi_async
  File "google/appengine/api/memcache/__init__.py", line 385, in _make_async_call
  File "google/appengine/api/memcache/__init__.py", line 297, in create_rpc
  File "google/appengine/api/apiproxy_stub_map.py", line 414, in __init__
  File "google/appengine/api/apiproxy_stub_map.py", line 68, in CreateRPC
AssertionError: No api proxy found for service "memcache"
```

**Comment by stevenle** [comment]
Tested using the packaged Linux build of `0.5.5` from https://github.com/grow/grow/releases, but I believe this was happening prior to that build.

**Comment by stevenle** [comment]
FWIW, this seems to only happen in the pre-packaged version of grow. I don't see this error when I install grow via a `virtualenv`.

Makes me wonder if there's a transitive 3rd-party dep that brings in `google.appengine` packages, which causes grow to think the user is on App Engine. Would be better to detect App Engine more deterministically in that case, though I can't verify what the root issue is.

**Comment by stevenle** [comment]
I tried to extract the pre-packaged version of `grow` (tried `unzip grow` but didn't seem to work). When I just view the executable with `vim`, I do see references to `google.appengine` in the Linux version but not the Mac version, so I'm guessing we just need to update our "is app engine check".

I'm guessing easiest would be to check the `os.environ.get('SERVER_SOFTWARE')` key per:
https://stackoverflow.com/questions/1916579/in-python-how-can-i-test-if-im-in-google-app-engine-sdk

**Comment by stevenle** [comment]
FYI I'm still getting the error above on `0.5.6` on Arch Linux.

```
Attempting refresh to obtain initial access_token
Traceback (most recent call last):
  File "bin/grow", line 76, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "grow/commands/subcommands/preprocess.py", line 42, in preprocess
  File "grow/pods/pods.py", line 778, in preprocess
  File "grow/preprocessors/google_drive.py", line 52, in run
  File "grow/preprocessors/google_drive.py", line 343, in execute
  File "grow/preprocessors/google_drive.py", line 192, in download
  File "grow/preprocessors/google_drive.py", line 48, in create_service
  File "site-packages/oauth2client/util.py", line 137, in positional_wrapper
  File "site-packages/googleapiclient/discovery.py", line 198, in build
  File "site-packages/oauth2client/transport.py", line 153, in new_request
  File "site-packages/oauth2client/contrib/appengine.py", line 178, in _refresh
  File "google/appengine/api/app_identity/app_identity.py", line 600, in get_access_token
  File "google/appengine/api/memcache/__init__.py", line 562, in get
  File "google/appengine/api/memcache/__init__.py", line 619, in get_multi_async
  File "google/appengine/api/memcache/__init__.py", line 385, in _make_async_call
  File "google/appengine/api/memcache/__init__.py", line 297, in create_rpc
  File "google/appengine/api/apiproxy_stub_map.py", line 414, in __init__
  File "google/appengine/api/apiproxy_stub_map.py", line 68, in CreateRPC
AssertionError: No api proxy found for service "memcache"
[6640] Failed to execute script grow
stevenle@archlinux:~/src/$ grow --version
0.5.6
```
