### ISSUE TITLE
Add tests for staging to Web Review on OSX and Linux

### ISSUE THREAD

**Issue by drGrove** [grow/grow#841]
Currently there are no tests to ensure that staging a grow build actually works. 

v0.5.4 Breaks staging on Mac OS High Sierra due to a keychain issues
Linux staging of grow builds has been broken since at least v0.3.0

**Comment by jeremydw** [comment]
Sample traceback:
```
➜  grow stage
Traceback (most recent call last):
  File "grow", line 76, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "grow/commands/subcommands/stage.py", line 68, in stage
  File "grow/deployments/destinations/webreview_destination.py", line 105, in deploy
  File "grow/deployments/destinations/base.py", line 279, in deploy
  File "grow/deployments/destinations/base.py", line 163, in _get_remote_index
  File "grow/deployments/destinations/base.py", line 232, in read_control_file
  File "grow/deployments/destinations/webreview_destination.py", line 133, in read_file
  File "site-packages/webreview/webreview.py", line 300, in read
  File "site-packages/webreview/webreview.py", line 277, in get_signed_requests
  File "site-packages/webreview/webreview.py", line 182, in get_service
  File "site-packages/webreview/webreview.py", line 223, in get_credentials
  File "site-packages/oauth2client/client.py", line 409, in get
  File "site-packages/oauth2client/contrib/keyring_storage.py", line 72, in locked_get
  File "site-packages/keyring/core.py", line 41, in get_password
  File "site-packages/keyring/backends/fail.py", line 23, in get_password
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
[51452] Failed to execute script grow
```

**Comment by drGrove** [comment]
Moved to grow/webreview-client#6
