### ISSUE TITLE
Failed to execute script grow , what is wrong ?

### ISSUE THREAD

**Issue by sunlight2728** [grow/grow#990]
grow install
Traceback (most recent call last):
  File "grow", line 76, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "grow/commands/subcommands/install.py", line 29, in install
  File "posixpath.py", line 73, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 21: ordinal not in range(128)
[64811] Failed to execute script grow

**Comment by sunlight2728** [comment]
grow run
Traceback (most recent call last):
  File "grow", line 76, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "grow/commands/subcommands/run.py", line 39, in run
  File "posixpath.py", line 73, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 21: ordinal not in range(128)
[68144] Failed to execute script grow

**Comment by Chilli-B** [comment]
I'm having the same issue. Version 0.8.11 macOS 10.14.3

Traceback (most recent call last):
  File "grow", line 76, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "grow/commands/subcommands/init.py", line 22, in init
  File "posixpath.py", line 73, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
[4143] Failed to execute script grow

**Comment by Zoramite** [comment]
What directory are you executing `grow init` in? Does the directory have any special characters in the path? For example, if you run `pwd` what does it display?

**Comment by Chilli-B** [comment]
Yes, there was a special character in the path. I changed the path, that solved the issue. Thanks!
