### ISSUE TITLE
grow translations extract should ignore .swp files

### ISSUE THREAD

**Issue by marchbox** [grow/grow#992]
VIM creates `.<filename>.<fileextension>.swp` file while you edit a file. If I run `grow translations extract --update` with a file open, I'll get the following error:

```
[16:02:50] Extracting: /views/partials/.contact-form.html.swp
Traceback (most recent call last):
  File "grow", line 76, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "grow/commands/subcommands/translations_extract.py", line 65, in translations_extract
  File "grow/translations/catalog_holder.py", line 427, in extract
  File "grow/translations/catalog_holder.py", line 291, in _babel_extract
  File "site-packages/babel/messages/extract.py", line 322, in extract
  File "site-packages/jinja2/ext.py", line 607, in babel_extract
  File "encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 16: invalid start byte
[22653] Failed to execute script grow
make: *** [strings] Error 255
```

**Comment by Zoramite** [comment]
@marchbox Can you check which version of grow you are on? Looking at the current codebase I can't see where this would be happening since we have a check to only extract the files that end in `.html` or in `.yaml` (See https://github.com/grow/grow/blob/master/grow/translations/catalog_holder.py#L436-L446).

**Comment by marchbox** [comment]
My current version is 0.8.8. Is it supposed to be using the logic in line 420? Since the file is under /views/ directory instead of /partials/? And it seems it only check if the file path starts with ".", but if the file is inside a subdirectory, it lets it pass.

**Comment by Zoramite** [comment]
Sorry, I had tried it first in the `views`, but didn't test in a sub directory so I didn't see the error. I have a fix so it should be in the next release.
